### ISSUE TITLE
Not closing electron

### ISSUE THREAD

**Issue by cha55son** [lele85/karma-electron-launcher#1]
When I run 

```
karma start config.js --single-run
```

karma doesn't close the browser after the tests are complete. Any idea on what's going on?

**Comment by lele85** [comment]
No idea... i made this runner with autowatch in mind. I will investigate.

**Comment by cha55son** [comment]
Figured out the issue. if I set the electron executable to:

```
export ELECTRON_BIN=./node_modules/.bin/electron
```

Then it has issues killing Electron. If I set it to:

```
export ELECTRON_BIN=./node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron
```

Then it works as expected. This may cause some issues with testing cross platform but i'll keep looking to see if there is a fix for that.
