### ISSUE TITLE
Electron-prebuilt is deprecated

### ISSUE THREAD

**Issue by vmike245** [lele85/karma-electron-launcher#13]
_electron-prebuilt_ is now deprecated and will stop being published at the end of 2016. The peer dependency should be changed to use _electron_.

**Comment by StefH** [comment]
Some more details:

> Note As of version 1.3.1, this package is published to npm under two names: electron and electron-prebuilt. You can currently use either name, but electron is recommended, as the electron-prebuilt name is deprecated, and will only be published until the end of 2016.

https://www.npmjs.com/package/electron-prebuilt
