### ISSUE TITLE
Publish 0.2.0

### ISSUE THREAD

**Issue by hypergeometric** [lele85/karma-electron-launcher#15]
Please can you look into publishing 0.2.0? I'm currently using a direct GitHub dependency but it's causing problems.

**Comment by princed** [comment]
Oh, I actually thought it's on npm already :(
@lele85 Could you please publish or add me to the package on npm?

**Comment by elwynelwyn** [comment]
+1. Currently published version on npm is broken. (package.json depends on `electron`, `index.js` imports from `electron-prebuilt`)

**Comment by lele85** [comment]
Done!
