### ISSUE TITLE
How to use with karma-babel?

### ISSUE THREAD

**Issue by trusktr** [lele85/karma-electron-launcher#18]
I'm using ES Modules in my app, and trying to add karma with karma-electron-launcher and karma-babel for testing.

Babel transpilation seems to work, but then when my test file tries to import a relative path, karma ends with an error like this:

```
Electron 1.8.6 (Linux 0.0.0) ERROR
  {
    "message": "An error was thrown in afterAll\nUncaught Error: Cannot find module './Mixin'\nUncaught Error: Cannot find module './TreeNode'",
    "str": "An error was thrown in afterAll\nUncaught Error: Cannot find module './Mixin'\nUncaught Error: Cannot find module './TreeNode'"
  }
```

How do I make relative paths work so that my test files can import them (using `require` after they are transpiled by karma-babel)?

**Comment by princed** [comment]
I'm sorry, but I'm afraid you might not get meaningful support from this repo maintainers at this stage.

**Comment by trusktr** [comment]
Alternatively, the author of [karma-electron](https://github.com/twolfson/karma-electron) is very responsive. Really awesome! 👍
